/******************************************************************************************************/
/***This code is used to write data into data file, with the same format of that generated by lammps***/
/***write_data command*********************************************************************************/
/******************************************************************************************************/
/*** SPECIAL NOTE:                                                                                  ***/
/*** (1) This code is designed to write only ONE snapshot each time. The data being written should  ***/
/***     be packed into a pre-defined data type, i.e. STEP type.                                    ***/
/*** (2) Current code only support following atom type: atomic, molecular, full.                    ***/
/******************************************************************************************************/
/***                                  HOW TO USE THIS CLASS                                         ***/
/*** To write a dump file:                                                                          ***/
/***                                                                                                ***/
/*** (1) Claim an object of WriteDump class:                                                        ***/
/***     WriteData()                                                                                ***/
/***       No argument is required.                                                                 ***/
/***                                                                                                ***/
/*** (2) Call following functions to write one snapshot of the file:                                ***/
/***     Write(string FileName, const STEP& cur_step, const char* atom_style)                       ***/
/***       Create a file named "FileName", and write data stored in "cur_step" into the file. User  ***/
/***       should specify the atom style.                                                           ***/
/******************************************************************************************************/
/*** Major revision:                                                                                ***/
/*** (1) Add: Write masses.                                                                         ***/
/******************************************************************************************************/
/*** Version: 11/12/2016 (1.1 Version) ***/
/*** By: Heyi Liang                    ***/
/*****************************************/

#ifndef WRITEDATA_H
#define WRITEDATA_H

#define WRITEDATA_VERSION "1.1"
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <cstring>
#include "Container.h"

using namespace std;

class WriteData
{
//    private:
//
    public:
        WriteData();
        ~WriteData();
        void print_version();

        /** public function that is used to write file **/
        int Write(string FileName, const STEP& cur_step, const char* atom_style); 
};

#endif // WRITEDATA_H
