/******************************************************************************************************/
/***This code is used to write data into dump file, with the same format of that generated by lammps***/
/***dump command***************************************************************************************/
/******************************************************************************************************/
/***SPECIAL NOTE: This code is designed to write only ONE snapshot each time. The data being written***/
/***should be packed into a pre-defined data type, i.e. STEP type.*************************************/
/******************************************************************************************************/
/***                                  HOW TO USE THIS CLASS                                         ***/
/*** To write a dump file:                                                                          ***/
/***                                                                                                ***/
/*** (1) Claim an object of WriteDump class:                                                        ***/
/***     WriteDump (string FileName, const vector<string>& Properties, const string& mode)          ***/
/***       string `FileName` is the name of output file, properties in vector<string> `Properties`  ***/
/***       will be written into the output file, string `mode` should be either "w" (for create/    ***/
/***       overwrite) or "a" (for append).                                                          ***/
/***                                                                                                ***/
/*** (2) Call following functions to write one snapshot of the file:                                ***/
/***     Write(const STEP& cur_step)                                                                ***/
/***       write data stored in STEP type object cur_step                                           ***/
/******************************************************************************************************/
/*** Major revision:                                                                                ***/
/*** (1) Modify:  Modified the constructor to include writing mode.                                 ***/
/******************************************************************************************************/
/*** Version: 11/15/2016 (1.1 Version)  ***/
/*** By: Heyi Liang                     ***/
/******************************************/

#ifndef WRITEDUMP_H
#define WRITEDUMP_H

#define WRITEDUMP_VERSION "1.1"
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <cstring>
#include "Container.h"

using namespace std;

class WriteDump
{
    private:
        string OutFileName;
        vector<string> OutProperties;
        vector<int> Index_OutProperties;

    public:
        WriteDump(string FileName, const vector<string>& Properties, const string& mode);
        ~WriteDump();
        void print_version();

        /** public function that is used to write file **/
        int Write(const STEP& cur_step);        // write data of one snapshots
};

#endif // WRITEDUMP_H
